# bundle exec jekyll serve --host=0.0.0.0

title: MycilaLogger
description: A simple and efficient logging library which is thread-safe and supports runtime level update
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
